import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, Check, CheckCheck, ChevronDown, CircleHelp, ClipboardList, FileText, FolderOpen, GitBranch, History, LayoutGrid, LoaderCircle, LockKeyhole, Maximize2, Minus, Plus, RotateCcw, Save, Send, Settings2, ShieldCheck, Sparkles, UnlockKeyhole, X } from 'lucide-react';
import { Diagram } from './Diagram';
import {TemplatePanel} from './TemplatePanel';
import {TEMPLATES,templateProposal} from './templates';
import {StyleSettings,describeChange} from './StyleSettings';
import { RunStream, type RunEvent, type RunSource, type RunStatus } from './RunStream';
import { registerDiagramTools } from './webmcp';
import { applyProposal, blockers, makeSnapshot, readSaved, restore, SAMPLES, type Kind, type Proposal } from './model';
import { useWorkspace } from './store';
const KEY='biaohui-demo-v1';
export default function App(){
 const {history,checked,dirty,replace,append,check,saved}=useWorkspace(); const current=history.at(-1);
 const [kind,setKind]=useState<Kind>('flowchart'),[text,setText]=useState(SAMPLES.flowchart.text),[title,setTitle]=useState(SAMPLES.flowchart.title),[bidMode,setBidMode]=useState('unknown'),[page,setPage]=useState('A4'),[orientation,setOrientation]=useState('portrait');
 const [panel,setPanel]=useState<'input'|'style'>('input'),[templateId,setTemplateId]=useState('classic');
 const [toast,setToast]=useState(''),[busy,setBusy]=useState(false),[proposal,setProposal]=useState<Proposal|null>(null),[modal,setModal]=useState<'export'|'help'|'replace'|'history'|null>(null),[png,setPng]=useState(''),[zoom,setZoom]=useState(100),[inputDirty,setInputDirty]=useState(false);
 const [runStatus,setRunStatus]=useState<RunStatus>('idle'),[runEvents,setRunEvents]=useState<RunEvent[]>([]),[runExpanded,setRunExpanded]=useState(false);
 const svgRef=useRef<SVGSVGElement>(null),dialogRef=useRef<HTMLDialogElement>(null);
 const notify=(message:string)=>setToast(message);
 useEffect(registerDiagramTools,[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty||inputDirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty,inputDirty]);
 useEffect(()=>{if(modal||proposal)dialogRef.current?.showModal();else dialogRef.current?.close()},[modal,proposal]);
 const errors=current?blockers(current):[];
 const preview=current??{...makeSnapshot(kind,title),appearance:{...TEMPLATES.find(t=>t.id===templateId)!.appearance}};
 function selectTemplate(id:string){if(current){const p=templateProposal(current,id);if(p.before!==p.after)setProposal(p);}else{setTemplateId(id);setInputDirty(true);}}
 function sample(k:Kind){setKind(k);setText(SAMPLES[k].text);setTitle(SAMPLES[k].title);setInputDirty(true);}
 const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
 const elapsed=(startedAt:number)=>`${((Date.now()-startedAt)/1000).toFixed(1)}s`;
 async function generate(force=false){
  if(!text.trim())return notify('请先输入业务内容。');
  if(text!==SAMPLES[kind].text)return notify('本演示只生成内置示例。请点击“载入示例”；自定义文本识别需要后续接入模型。');
  if(current&&!force){setModal('replace');return;}
  setModal(null);setBusy(true);setRunStatus('running');setRunEvents([]);
  const startedAt=Date.now();let eventId=0;
  const pushEvent=(source:RunSource,message:string,level:RunEvent['level']='info')=>setRunEvents(events=>[...events,{id:++eventId,elapsed:elapsed(startedAt),source,message,level}]);
  try{
   pushEvent('程序','已接收图表生成请求');
   await wait(320);pushEvent('程序','正在整理业务步骤与页面参数');
   await wait(420);pushEvent('LLM','正在分析内容并生成图表结构');
   await wait(620);pushEvent('LLM',kind==='flowchart'?'已返回 8 个节点及整改回路':'已返回 3 项任务及依赖关系','success');
   await wait(380);pushEvent('程序','结构校验通过，正在准备预览','success');
   await wait(450);pushEvent('渲染器','正在计算布局并绘制图形');
   await wait(460);
   const s={...makeSnapshot(kind,title),appearance:{...preview.appearance},bidMode,page,orientation,revision:current?current.revision+1:1};
   if(current)append(s);else replace([s]);setInputDirty(false);
   pushEvent('渲染器','预览已生成，可继续编辑','success');setRunStatus('success');
   notify('示例草稿已生成，可直接编辑或选择右侧样式模板。');
  }catch(e){
   pushEvent('程序',(e as Error).message||'生成过程中断','error');setRunStatus('error');setRunExpanded(true);notify('生成失败，请展开运行详情查看。');
  }finally{setBusy(false);}
 }
 function apply(){if(!current||!proposal)return;try{append(applyProposal(current,proposal));setProposal(null);notify('修改已应用，已保留上一版。');}catch(e){notify((e as Error).message)}}
 function save(){try{localStorage.setItem(KEY,JSON.stringify(history));saved();notify('图表版本已保存到当前浏览器；未生成的输入不在保存范围内。')}catch{notify('浏览器存储不可用，保存失败。')}}
 function reopen(){if(dirty||inputDirty){if(!window.confirm('打开已保存的项目会替换当前未保存内容，是否继续？'))return;}try{const raw=localStorage.getItem(KEY);if(!raw)return notify('还没有保存的项目。先生成并保存一份图表。');const h=readSaved(raw);replace(h,false);const s=h.at(-1)!;setKind(s.kind);setTitle(s.title);setText(s.source);setBidMode(s.bidMode);setPage(s.page);setOrientation(s.orientation);setInputDirty(false);notify('已打开浏览器中保存的项目。')}catch{notify('保存的数据无法读取，当前内容未更改。')}}
 async function exportPreview(){if(!current)return notify('请先生成图表草稿。');check();if(blockers(current).length)return notify('当前图表存在阻断问题，请处理后再下载。');
  try{await document.fonts.ready;const clone=svgRef.current!.cloneNode(true) as SVGSVGElement;clone.querySelectorAll('[data-editor]').forEach(node=>node.remove());const svg=new XMLSerializer().serializeToString(clone);const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml;charset=utf-8'}));
   try{const img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(new Error('图片渲染失败，请重试。'));img.src=url});const canvas=document.createElement('canvas');canvas.width=1890;canvas.height=Math.round(1890*(current.kind==='flowchart'?660/760:420/900));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('此浏览器暂不支持图片导出。');ctx.fillStyle=current.appearance.backgroundColor;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);setPng(canvas.toDataURL('image/png'));setModal('export');}finally{URL.revokeObjectURL(url)}
  }catch(e){notify((e as Error).message)}
 }
 const stage=!current?0:checked===current.revision?2:1;
 return <div className="app-shell">
  <aside className="rail"><a className="brand-mark" href="#" aria-label="标绘工作台"><GitBranch size={24}/></a><div className="rail-divider"/><button className="rail-item active" aria-label="图表工作台" onClick={()=>setPanel('input')}><LayoutGrid size={21}/><span>工作台</span></button><button className="rail-item" onClick={reopen} aria-label="打开已保存项目"><FolderOpen size={21}/><span>本地项目</span></button><button className="rail-item" onClick={()=>setModal('history')}><History size={21}/><span>版本记录</span></button><div className="rail-bottom"><button className="rail-item" onClick={()=>setModal('help')}><CircleHelp size={21}/><span>使用说明</span></button><div className="avatar">演示</div></div></aside>
  <div className="workspace"><header><div className="header-title"><strong>标绘<span> / </span></strong><span>标书图表工作台</span><span className="demo-badge">交互 Demo</span></div><div className="header-actions"><span className="save-status"><i/>{dirty?'有未保存的图表':current?'已保存到本机':'本地演示空间'}</span><button className="button" disabled={!current} onClick={save}><Save size={16}/>保存项目</button><button className="button primary" disabled={!current} onClick={exportPreview}><ArrowDownToLine size={16}/>下载草稿 PNG</button></div></header>
  <div className="project-heading"><div><div className="eyebrow">DIAGRAM STUDIO</div><h1>把方案，变成清晰的图表。</h1><p>从业务内容到文档插图，每一步都可核对、可修改。</p></div><div className="local-pill"><span/>模拟数据 · 无需连接后端</div></div>
  <nav className="steps" aria-label="制作流程">{['输入内容','预览与修改','检查与下载'].map((label,i)=><div className={i===stage?'step selected':i<stage?'step done':'step'} key={label}><span className="step-number">{i<stage?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><span>{label}</span>{i<2&&<span className="step-line"/>}</div>)}</nav>
  <main className="editor-grid"><section className="input-panel panel"><div className="panel-tabs"><button className={panel==='input'?'selected':''} onClick={()=>setPanel('input')}><FileText size={16}/>内容输入</button><button className={panel==='style'?'selected':''} onClick={()=>setPanel('style')}><Settings2 size={16}/>版式设置</button></div>
   <div className="input-scroll">{panel==='input'?<><div className="field-label">图表类型 <span className="required">*</span></div><div className="kind-picker"><button className={kind==='flowchart'?'selected':''} onClick={()=>sample('flowchart')}><GitBranch size={20}/><span>流程图</span>{kind==='flowchart'&&<Check size={14}/>}</button><button className={kind==='gantt'?'selected':''} onClick={()=>sample('gantt')}><ClipboardList size={20}/><span>甘特图</span>{kind==='gantt'&&<Check size={14}/>}</button></div>
   <label className="field-label" htmlFor="title">图题</label><input id="title" value={title} onChange={e=>{setTitle(e.target.value);setInputDirty(true)}} placeholder="为这张图表命名"/>
   <label className="field-label" htmlFor="bid-mode">技术标类型 <span className="required">*</span></label><select id="bid-mode" value={bidMode} onChange={e=>{setBidMode(e.target.value);setInputDirty(true)}}><option value="unknown">尚不确定</option><option value="open">明标</option><option value="blind">暗标</option></select>
   <div className="field-label field-row"><label htmlFor="business">业务内容 <span className="required">*</span></label><button className="text-button" onClick={()=>sample(kind)}>载入示例 <ArrowRight size={13}/></button></div><textarea id="business" className="business-text" value={text} onChange={e=>{setText(e.target.value);setInputDirty(true)}}/><div className="input-caption">粘贴业务描述、步骤与依赖关系<span>{text.length} 字</span></div>
   <div className="source-note"><CircleHelp size={14}/><span>当前为内置示例，内容不代表真实项目要求。</span></div></>:<><h3>文档插图版式</h3><p className="muted">默认值仅用于演示，以实际招标规则为准。</p><label className="field-label" htmlFor="paper">目标纸型</label><select id="paper" value={page} onChange={e=>{setPage(e.target.value);setInputDirty(true)}}><option>A4</option><option>A3</option></select><label className="field-label" htmlFor="orientation">页面方向</label><select id="orientation" value={orientation} onChange={e=>{setOrientation(e.target.value);setInputDirty(true)}}><option value="portrait">竖向</option><option value="landscape">横向</option></select><div className="setting-summary"><span>插入宽度<strong>160 mm</strong></span><span>输出分辨率<strong>300 DPI</strong></span><span>配色<strong>支持自定义</strong></span></div><label className="field-label" htmlFor="font-size">图内字号</label><select id="font-size" value={current?.fontSize??12} disabled={!current} onChange={e=>current&&setProposal({baseRevision:current.revision,field:'fontSize',before:current.fontSize,after:Number(e.target.value),impact:'全图文字统一调整；业务内容不变。确认后需重新检查。'})}><option value="12">12 磅</option><option value="14">14 磅</option><option value="16">16 磅</option></select><p className="source-note">字号调整会先展示差异。纸型和方向在重新生成时记录，实际纸面适配仍待验证。</p><StyleSettings snapshot={current} onPropose={setProposal}/></>}
   </div><div className="generate-footer"><button className="button primary generate" disabled={busy} onClick={()=>generate()}>{busy?<LoaderCircle size={18} className="spin"/>:<Sparkles size={18}/>} {busy?'正在载入示例…':current?'重新生成草稿':'生成图表草稿'}<ArrowRight size={17}/></button><span>示例生成 · 不调用 AI 服务</span></div>
  </section>
  <section className="preview-panel panel"><div className="preview-toolbar"><div><span className="status-dot"/><strong>图表预览</strong><span className="sub-badge">{current?`v${current.revision}`:'示例'}</span></div><div className="canvas-toolbar-actions"><button className="icon-button" disabled={!current} title={current?.locked?'解除业务内容保护':'保护业务内容'} aria-label={current?.locked?'解除业务内容保护':'保护业务内容'} aria-pressed={current?.locked??false} onClick={()=>append({...current!,locked:!current!.locked,revision:current!.revision+1})}>{current?.locked?<LockKeyhole size={17}/>:<UnlockKeyhole size={17}/>}</button><button className="icon-button" title="恢复适配视图" aria-label="恢复适配视图" onClick={()=>setZoom(100)}><Maximize2 size={17}/></button></div></div><RunStream status={runStatus} events={runEvents} expanded={runExpanded} onExpandedChange={setRunExpanded}/>{current&&checked===current.revision&&<div className={errors.length?"canvas-check-result has-errors":"canvas-check-result"} role="status">{errors.length?errors.join(" "):"演示检查完成 · 实际项目适用性未核验"}</div>}<div className="canvas-area"><div className="canvas-info"><span>{current?.page??page} · {(current?.orientation??orientation)==='portrait'?'竖向':'横向'} · 160 mm</span><span>{current?'工作草稿':'示例效果预览'}</span></div><div className="paper-wrap"><div className={'paper '+((current?.kind??kind)==='gantt'?'gantt-paper':'')} style={{width:`${zoom}%`,background:preview.appearance.backgroundColor}}><div className="paper-heading" style={{fontFamily:preview.appearance.fontFamily,color:preview.appearance.textColor}}>{current?.title??title}</div><Diagram key={current?.revision??`preview-${kind}`} snapshot={preview} svgRef={svgRef} onPropose={current?setProposal:undefined}/></div></div><div className="canvas-bottom"><span><LockKeyhole size={13}/>{!current?'生成后可编辑':current.kind==='flowchart'?'双击文字编辑 · 拖动节点调整位置':'双击任务名称编辑 · 工期定位'}</span><div className="zoom-controls"><button aria-label="缩小" disabled={zoom<=60} onClick={()=>setZoom(z=>z-10)}><Minus size={14}/></button><span>{zoom}%</span><button aria-label="放大" disabled={zoom>=150} onClick={()=>setZoom(z=>z+10)}><Plus size={14}/></button></div></div></div>
  </section>
  <TemplatePanel snapshot={preview} onSelect={selectTemplate} onCustomize={()=>setPanel('style')}/>
  </main><footer className="workspace-footer"><span><ShieldCheck size={13}/>资料仅留在当前浏览器 · 保存需手动操作</span><span>PNG 图片输出 <span className="footer-dot">·</span> 自定义文档插图</span></footer>
  </div>{toast&&<div role="status" className="toast"><CircleHelp size={18}/>{toast}<button aria-label="关闭提示" onClick={()=>setToast('')}><X size={15}/></button></div>}
  <dialog ref={dialogRef} onCancel={()=>{setModal(null);setProposal(null)}}><button className="dialog-close icon-button" aria-label="关闭弹窗" onClick={()=>{setModal(null);setProposal(null)}}><X size={20}/></button>{proposal?<><div className="dialog-symbol"><GitBranch size={24}/></div><h2>确认本次修改</h2><p className="muted">基于 v{proposal.baseRevision}，确认后创建新版本。</p><div className="diff-row"><span>修改前</span><del>{describeChange(proposal.before,proposal.field)}{proposal.field==='duration'?' 天':proposal.field==='fontSize'?' 磅':''}</del></div><div className="diff-row after"><span>修改后</span><strong>{describeChange(proposal.after,proposal.field)}{proposal.field==='duration'?' 天':proposal.field==='fontSize'?' 磅':''}</strong></div><div className="impact"><strong>影响范围</strong><p>{proposal.impact}</p></div><div className="dialog-actions"><button className="button" onClick={()=>setProposal(null)}>取消</button><button className="button primary" onClick={apply}>确认并应用 <Check size={16}/></button></div></>:modal==='export'?<><h2>PNG 实际输出预览</h2><p className="muted">v{current?.revision} · 宽 1890 px · 建议插入宽度 160 mm</p><div className="export-image"><img src={png} alt="即将下载的实际 PNG 草稿"/></div><p className="scope-note">仅供演示的工作草稿；实际项目合规性与字体未核验。图题不写入图片。</p><div className="dialog-actions"><button className="button" onClick={()=>setModal(null)}>返回编辑</button><a className="button primary" href={png} download={`标绘-演示草稿-v${current?.revision}.png`} onClick={()=>notify('已发起 PNG 下载，请在浏览器下载列表查看。')}><ArrowDownToLine size={16}/>下载草稿 PNG</a></div></>:modal==='history'?<><h2>版本记录</h2><p className="muted">每次应用修改创建新版本，保留历史。</p>{history.length===0?<p className="empty-history">尚未生成图表。</p>:[...history].reverse().map((item,i)=><div className="version-card" key={item.revision}><div><strong>v{item.revision}</strong>{i===0&&<span className="small-tag">当前版本</span>}</div><p>{item.title}</p><span>{item.kind==='flowchart'?'流程图':`甘特图 · ${item.duration+3} 天`} · {item.fontSize} 磅</span></div>)}<button className="button full" disabled={history.length<2} onClick={()=>{append(restore(history));setModal(null);notify('已恢复上一版内容，保存为新版本。');}}><RotateCcw size={15}/>恢复上一版</button></>:modal==='replace'?<><h2>重新生成示例草稿？</h2><p className="muted">将使用左侧内容、图题和版式创建新版本。当前预览中的修改不会带入新草稿，历史版本保留。</p><div className="dialog-actions"><button className="button" onClick={()=>setModal(null)}>继续编辑</button><button className="button primary" onClick={()=>generate(true)}>确认重新生成</button></div></>:<><div className="dialog-symbol"><Sparkles size={24}/></div><h2>体验一张图表的完整流程</h2><ol className="help-steps"><li>选择流程图或甘特图，载入内置示例。</li><li>生成草稿，从右侧缩略图选择样式模板。</li><li>双击节点改文字、拖动节点，或在版式设置中调整字体与颜色；核对差异后应用。</li><li>检查当前版本，预览并下载 PNG 草稿。</li></ol><p className="scope-note">本 Demo 不连接后端或模型。自定义文本理解、真实规则提取、正式排期与合规校验尚未接入。保存仅保存在当前浏览器。</p><button className="button primary full" onClick={()=>setModal(null)}>开始体验 <ArrowRight size={16}/></button></>}</dialog>
 </div>
}
